// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhe7Gpdln-PKJ4HKnW1jZHvoeNfPiOAzw',
    appId: '1:409419825888:android:ae6ee6fa158b85e8fe0685',
    messagingSenderId: '409419825888',
    projectId: 'fir-oceans',
    storageBucket: 'fir-oceans.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zSYT3EEu_TFmNO6jKRqZ_Yx67a8kNLc',
    appId: '1:409419825888:web:5d839e500c52d683fe0685',
    messagingSenderId: '409419825888',
    projectId: 'fir-oceans',
    authDomain: 'fir-oceans.firebaseapp.com',
    storageBucket: 'fir-oceans.appspot.com',
    measurementId: 'G-QYFYYGV8N3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXhxvGMuk323Q0J1N3nokF57dPRP4SfbY',
    appId: '1:409419825888:ios:6c0f4e35a6a05453fe0685',
    messagingSenderId: '409419825888',
    projectId: 'fir-oceans',
    storageBucket: 'fir-oceans.appspot.com',
    iosBundleId: 'com.example.dwBarbershop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhxvGMuk323Q0J1N3nokF57dPRP4SfbY',
    appId: '1:409419825888:ios:6c0f4e35a6a05453fe0685',
    messagingSenderId: '409419825888',
    projectId: 'fir-oceans',
    storageBucket: 'fir-oceans.appspot.com',
    iosBundleId: 'com.example.dwBarbershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zSYT3EEu_TFmNO6jKRqZ_Yx67a8kNLc',
    appId: '1:409419825888:web:2e34d702126c5115fe0685',
    messagingSenderId: '409419825888',
    projectId: 'fir-oceans',
    authDomain: 'fir-oceans.firebaseapp.com',
    storageBucket: 'fir-oceans.appspot.com',
    measurementId: 'G-QTP3KSBPL3',
  );

}